"""Native human-readable graph data and lossless polynomial interning."""
import argparse,json
from pathlib import Path
from checks import dump


def main():
    ap=argparse.ArgumentParser();ap.add_argument('--out',required=True);a=ap.parse_args();out=Path(a.out)
    pool=[];index={}
    def ref(p):
        t=tuple(p)
        if t not in index:index[t]=len(pool);pool.append(list(p))
        return index[t]
    def graph(g,full=False):
        r={k:g[k] for k in ['id','n','edges','U','D','HEREDITARY'] if k in g}
        r['P']=ref(g['P']);r['full_vertex_data']=full
        if full:r['A']=[ref(p) for p in g['A']];r['B']=[ref(p) for p in g['B']]
        return r
    mats=json.loads((out/'interaction_material.json').read_text())+json.loads((out/'discovery_material.json').read_text())
    graphs=[graph(g,full=g['id']=='old23') for g in mats]
    w=json.loads((out/'mode_witness.json').read_text());wm=dict(w)
    for k in ['A','B_before','B_after','P_cut_before','P_cut_after','original_P']:wm[k]=ref(w[k])
    bw=json.loads((out/'boundary_witness.json').read_text());roots=[]
    for side in ['left','right']:
        g=dict(bw[side]);g['id']='root9_'+side;r=graph(g,full=True)
        r['joint_profiles']={v:[ref(p) for p in qs] for v,qs in bw['joint_'+side]['vertices'].items()};roots.append(r)
    native=dict(format='phase5-polynomial-pool-v1',polynomials=pool,graphs=graphs,
         mode_witness=wm,rooted_pair=roots,rooted_X=bw['X'],rooted_Y=bw['Y'],
         limitation='Pool references restore full original arrays including trailing zeros. Graphs with full_vertex_data=false contain P only here. ALL larger A/B, cut and completion arrays are in the archive and regenerated by the native sources; they are not represented as Git-hosted.')
    # Lossless equality checks, not just hash comparison.
    for original,saved in zip(mats,graphs):
        assert original['P']==pool[saved['P']]
        if saved['full_vertex_data']:
            for k in ['A','B']:assert original[k]==[pool[z] for z in saved[k]]
    for k in ['A','B_before','B_after','P_cut_before','P_cut_after','original_P']:assert w[k]==pool[wm[k]]
    for side,saved in zip(['left','right'],roots):
        assert bw[side]['P']==pool[saved['P']]
        for k in ['A','B']:assert bw[side][k]==[pool[z] for z in saved[k]]
        assert bw['joint_'+side]['vertices']=={v:[pool[z] for z in refs] for v,refs in saved['joint_profiles'].items()}
    summary=dict(pool_size=len(pool),graph_count=len(graphs),full_vertex_graphs=sum(g['full_vertex_data'] for g in graphs)+len(roots),
                 full_rooted_joint_profiles=18,full_decoded_arrays_equal=True,raw_large_arrays_Git_hosted=False)
    dump(out/'NATIVE_EVIDENCE.json',native);dump(out/'native_summary.json',summary);print(json.dumps(summary,indent=2))

if __name__=='__main__':main()
