#!/usr/bin/env python3
"""Lossless complete H64 P/A/B pool plus compact, scoped run records.
Unpooled discovery arrays are separately reproducible, not silently Git-hosted.
"""
from pathlib import Path
import hashlib,json
BASE=Path(__file__).resolve().parents[1]
def load(name): return json.loads((BASE/'certificates'/name).read_text())
def main():
    h=load('terminal64_witness.json'); pool=[]; ids={}
    def intern(p):
        key=tuple(p)
        if key not in ids: ids[key]=len(pool); pool.append(p)
        return ids[key]
    refs=[]; modegroups={}
    for v in h['vertices']:
        refs.append([v['v'],intern(v['A']),intern(v['B'])])
        key=(tuple(v['A_modes']),tuple(v['B_modes']))
        modegroups.setdefault(key,[]).append(v['v'])
    witness={k:h[k] for k in ('n','edges','HEREDITARY','unimodal','log_concave','U','D','valleys','residual_pairs','role')}
    witness.update(P_pool=intern(h['P']),vertex_pool_refs=refs,polynomial_pool=pool,
      vertex_pool_schema=['vertex','A_pool_index','B_pool_index'],
      mode_groups=[{'vertices':vs,'A':a,'B':b} for (a,b),vs in modegroups.items()],
      terminal_centers=[t['center'] for t in h['terminal_spiders']])
    for v,(_,a,b) in zip(h['vertices'],refs):
        assert v['A']==pool[a] and v['B']==pool[b]
    d=load('directed_search_full.json')
    schema=['id','n','component_orders','U','D','HEREDITARY','canonical_sha256']
    rows=[[r[k] for k in schema] for r in d['records']]
    large=load('large_block_obstruction.json'); lc={k:v for k,v in large.items() if k!='checks'}
    lc['check_schema']=['k','r','component_order','degree','top_minor','full_sequence_unimodal','U','D','residual_pairs']
    lc['checks']=[[r[k] for k in lc['check_schema']] for r in large['checks']]
    raw=['terminal64_witness.json','directed_search_full.json','large_block_obstruction.json']
    out={'H64':witness,'hereditary64_summary':load('hereditary64_summary.json'),
      'external_selected_check':load('external_selected_check.json'),
      'directed_summary':load('directed_search_summary.json'),'directed_record_schema':schema,'directed_records':rows,
      'large_block_obstruction':lc,'regressions':load('regressions.json'),
      'omitted_raw_arrays':{f:hashlib.sha256((BASE/'certificates'/f).read_bytes()).hexdigest() for f in raw},
      'hosting_boundary':'Full H64 P/A/B arrays and every vertex are retained losslessly; directed and formula records are compact. Raw files are regenerated by src and included in the delivery ZIP, not asserted Git-hosted.'}
    (BASE/'certificates/NATIVE_CERTIFICATE.json').write_text(json.dumps(out,sort_keys=True,separators=(',',':'))+'\n')
    print('PASS: H64 lossless polynomial pool; compact records',len(rows),'pool size',len(pool))
if __name__=='__main__': main()
